services:
  prometheus:
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    image: ${PROMETHEUS_IMAGE_NAME}:${PROMETHEUS_IMAGE_VERSION}
    ports:
      - "${PROMETHEUS_HOST_PORT}:${PROMETHEUS_CONT_PORT}"
    volumes:
      - ${PROMETHEUS_HOST_CONFIG_PATH}:${PROMETHEUS_CONT_CONFIG_PATH}
      - ${PROMETHEUS_HOST_DATA_PATH}:/${PROMETHEUS_CONT_DATA_PATH}
    restart: unless-stopped
    networks:
      - app-network
  pushgateway:
    container_name: ${PUSHGATEWAY_CONTAINER_NAME}
    image: ${PUSHGATEWAY_IMAGE_NAME}:${PUSHGATEWAY_IMAGE_VERSION}
    ports:
      - "${PUSHGATEWAY_HOST_PORT}:${PUSHGATEWAY_CONT_PORT}"
    volumes:
      - ${PUSHGATEWAY_HOST_DATA_PATH}:${PUSHGATEWAY_CONT_DATA_PATH}
    command:
      - --persistence.file=/prometheus/pushgateway_metrics.db
    restart: unless-stopped
    networks:
      - app-network
  grafana:
    container_name: ${GRAFANA_CONTAINER_NAME}
    image: ${GRAFANA_IMAGE_NAME}:${GRAFANA_IMAGE_VERSION}
    ports:
      - "${GRAFANA_HOST_PORT}:${GRAFANA_CONT_PORT}"
    volumes:
      - ${GRAFANA_HOST_DATA_PATH}:${GRAFANA_CONT_DATA_PATH}
      - ${GRAFANA_HOST_CONFIG_PATH}:${GRAFANA_CONT_CONFIG_PATH}
      - ${GRAFANA_HOST_LOG_PATH}:${GRAFANA_CONT_LOG_PATH}
    restart: unless-stopped
    networks:
      - app-network
  node_exporter:
    container_name: ${EXPORTER_CONTAINER_NAME}
    image: ${EXPORTER_IMAGE_NAME}:${EXPORTER_IMAGE_VERSION}
    pid: host
    ports:
      - "${EXPORTER_HOST_PORT}:${EXPORTER_CONT_PORT}"
    volumes:
      - ${EXPORTER_HOST_ROOT_PATH}:${EXPORTER_CONT_ROOT_PATH}:ro
      - ${EXPORTER_HOST_PROC_PATH}:${EXPORTER_CONT_PROC_PATH}:ro
      - ${EXPORTER_HOST_SYS_PATH}:${EXPORTER_CONT_SYS_PATH}:ro
      - ${EXPORTER_HOST_RUN_PATH}:${EXPORTER_CONT_RUN_PATH}:rw
      - ${EXPORTER_HOST_MACHINE_ID_PATH}:${EXPORTER_CONT_MACHINE_ID_PATH}:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.netclass.ignored-devices=^(veth.*|docker.*|br-.*)$$'
    restart: unless-stopped
    networks:
      - app-network
  cadvisor:
    container_name: ${CADVISOR_CONTAINER_NAME}
    image: ${CADVISOR_IMAGE_NAME}:${CADVISOR_IMAGE_VERSION}
    ports:
      - "${CADVISOR_HOST_PORT}:${CADVISOR_CONT_PORT}"
    volumes:
      - ${CADVISOR_HOST_ROOT_PATH}:${CADVISOR_CONT_ROOT_PATH}:ro
      - ${CADVISOR_HOST_RUN_PATH}:${CADVISOR_CONT_RUN_PATH}:ro
      - ${CADVISOR_HOST_SYS_PATH}:${CADVISOR_CONT_SYS_PATH}:ro
      - ${CADVISOR_HOST_DOCKER_PATH}:${CADVISOR_CONT_DOCKER_PATH}:ro
      - ${CADVISOR_HOST_DISK_PATH}:${CADVISOR_CONT_DISK_PATH}:ro
    privileged: true
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge