services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_IMAGE}:${REDIS_IMAGE_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONT_PORT}"
    volumes:
      - ${REDIS_HOST_PATH_CONFIG}:${REDIS_CONT_PATH_CONFIG}
      - ${REDIS_HOST_PATH_DATA}:${REDIS_CONT_PATH_DATA}
    command: ${REDIS_COMMAND}
    privileged: true
    restart: unless-stopped
    networks:
      - app-network
  rabbitmq:
    container_name: ${RABBITMQ_CONTAINER_NAME}
    image: ${RABBITMQ_IMAGE}:${RABBITMQ_IMAGE_VERSION}
    ports:
      - "${RABBITMQ_HOST_PORT}:${RABBITMQ_CONT_PORT}"
      - "${RABBITMQ_HOST_MGMT_PORT}:${RABBITMQ_CONT_MGMT_PORT}"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ${RABBITMQ_HOST_PATH_DATA}:${RABBITMQ_CONT_PATH_DATA}
    restart: unless-stopped
    networks:
      - app-network
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: ${MYSQL_IMAGE}:${MYSQL_IMAGE_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONT_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_HOST_PATH_CONFIG}:${MYSQL_CONT_PATH_CONFIG}
      - ${MYSQL_HOST_PATH_DATA}:${MYSQL_CONT_PATH_DATA}
    restart: unless-stopped
    networks:
      - app-network
  nacos:
    container_name: ${NACOS_CONTAINER_NAME}
    image: ${NACOS_IMAGE}:${NACOS_IMAGE_VERSION}
    ports:
      - "${NACOS_HOST_PORT}:${NACOS_CONT_PORT}"
      - "${NACOS_HOST_GRPC_PORT}:${NACOS_CONT_GRPC_PORT}"
    environment:
      - MODE=${NACOS_MODE}
    volumes:
      - ${NACOS_HOST_CONF_PATH}:${NACOS_CONT_CONF_PATH}
      - ${NACOS_HOST_DATA_PATH}:${NACOS_CONT_DATA_PATH}
      - ${NACOS_HOST_LOGS_PATH}:${NACOS_CONT_LOGS_PATH}
    restart: unless-stopped
    networks:
      - app-network
  sentinel:
    container_name: ${SENTINEL_CONTAINER_NAME}
    image: ${SENTINEL_IMAGE}:${SENTINEL_IMAGE_VERSION}
    ports:
      - "${SENTINEL_HOST_PORT}:${SENTINEL_CONT_PORT}"
      - "${SENTINEL_HOST_CLIENT_PORT}:${SENTINEL_CONT_CLIENT_PORT}"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - nacos
  etcd-host-0:
    container_name: ${ETCD0_CONTAINER_NAME}
    image: ${ETCD0_IMAGE_NAME}:${ETCD0_IMAGE_VERSION}
    network_mode: host
    volumes:
      - ${ETCD0_HOST_CONFIG_PATH}:${ETCD0_CONT_CONFIG_PATH}
      - ${ETCD0_HOST_DATA_PATH}:${ETCD0_CONT_DATA_PATH}
    entrypoint:
      - '${ETCD0_CONT_BINARY_BATH}'
    command:
      - '--config-file'
      - '${ETCD0_CONT_CONFIG_PATH}'
    restart: unless-stopped
  etcd-host-1:
    container_name: ${ETCD1_CONTAINER_NAME}
    image: ${ETCD1_IMAGE_NAME}:${ETCD1_IMAGE_VERSION}
    network_mode: host
    volumes:
      - ${ETCD1_HOST_CONFIG_PATH}:${ETCD1_CONT_CONFIG_PATH}
      - ${ETCD1_HOST_DATA_PATH}:${ETCD1_CONT_DATA_PATH}
    entrypoint:
      - '${ETCD1_CONT_BINARY_BATH}'
    command:
      - '--config-file'
      - '${ETCD1_CONT_CONFIG_PATH}'
    restart: unless-stopped
  etcd-host-2:
    container_name: ${ETCD2_CONTAINER_NAME}
    image: ${ETCD2_IMAGE_NAME}:${ETCD2_IMAGE_VERSION}
    network_mode: host
    volumes:
      - ${ETCD2_HOST_CONFIG_PATH}:${ETCD2_CONT_CONFIG_PATH}
      - ${ETCD2_HOST_DATA_PATH}:${ETCD2_CONT_DATA_PATH}
    entrypoint:
      - '${ETCD2_CONT_BINARY_BATH}'
    command:
      - '--config-file'
      - '${ETCD2_CONT_CONFIG_PATH}'
    restart: unless-stopped

networks:
  app-network:
    driver: bridge