services:
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: ${REDIS_IMAGE}:${REDIS_IMAGE_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    volumes:
      - ${REDIS_HOST_PATH_CONFIG}:${REDIS_CONT_PATH_CONFIG}
      - ${REDIS_HOST_PATH_DATA}:${REDIS_CONT_PATH_DATA}
    command: ${REDIS_COMMAND}
    privileged: true
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge