#!/bin/bash

# path on node and project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_CONFIG_DIR="${SCRIPT_DIR}/../service-config"

PROMETHEUS_PROJECT_DIR="${SERVICE_CONFIG_DIR}/prometheus"
PROMETHEUS_PROJECT_CONFIG_FILE="${PROMETHEUS_PROJECT_DIR}/prometheus.yml"
PROMETHEUS_DST_DIR="/app/prometheus/config"
PROMETHEUS_DST_CONFIG_FILE="${PROMETHEUS_DST_DIR}/prometheus.yml"
PROMETHEUS_DST_CONFIG_FILE_BAK="${PROMETHEUS_DST_DIR}/prometheus.yml.bak"

# Grafana project path
GRAFANA_PROJECT_DIR="${SERVICE_CONFIG_DIR}/grafana"
GRAFANA_PROJECT_PROVISIONING_DIR="${GRAFANA_PROJECT_DIR}/provisioning"
GRAFANA_PROJECT_DATASOURCE_DIR="${GRAFANA_PROJECT_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_PROJECT_DASHBOARDS_DIR="${GRAFANA_PROJECT_PROVISIONING_DIR}/dashboards"
GRAFANA_PROJECT_DASHBOARDS_FILE="${GRAFANA_PROJECT_DASHBOARDS_DIR}/dashboards.yml"
GRAFANA_PROJECT_PANEL_DIR="${GRAFANA_PROJECT_DASHBOARDS_DIR}/panel"
GRAFANA_PROJECT_PANEL_CADVISOR_FILE="${GRAFANA_PROJECT_PANEL_DIR}/cadvisor.json"
GRAFANA_PROJECT_PANEL_NODE_EXPORTER_FILE="${GRAFANA_PROJECT_PANEL_DIR}/node-exporter.json"
# Grafana node path
GRAFANA_DST_DIR="/app/grafana/config/grafana"
GRAFANA_DST_PROVISIONING_DIR="${GRAFANA_DST_DIR}/provisioning"
GRAFANA_DST_DATASOURCE_FILE="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_DST_DATASOURCE_FILE_BAK="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml.bak"
GRAFANA_DST_DASHBOARDS_DIR="${GRAFANA_DST_PROVISIONING_DIR}/dashboards"
GRAFANA_DST_DASHBOARDS_FILE="${GRAFANA_DST_DASHBOARDS_DIR}/dashboards.yml"
GRAFANA_DST_DASHBOARDS_FILE_BAK="${GRAFANA_DST_DASHBOARDS_DIR}/dashboards.yml.bak"
GRAFANA_DST_PANEL_DIR="${GRAFANA_DST_DASHBOARDS_DIR}/panel"
GRAFANA_DST_PANEL_DEFAULT_FILE="${GRAFANA_DST_PANEL_DIR}/cadvisor.json"
GRAFANA_DST_PANEL_DEFAULT_FILE_BAK="${GRAFANA_DST_PANEL_DIR}/cadvisor.json.bak"
GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER="${GRAFANA_DST_PANEL_DIR}/node-exporter.json"
GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER_BAK="${GRAFANA_DST_PANEL_DIR}/node-exporter.json.bak"

# ETCD config
# ETCD project path, file create by config-preload-etcd.sh
ETCD_PROJECT_DIR="${SERVICE_CONFIG_DIR}/etcd"
ETCD_PROJECT_CONFIG_0="${ETCD_PROJECT_DIR}/etcd0.yaml"
ETCD_PROJECT_CONFIG_1="${ETCD_PROJECT_DIR}/etcd1.yaml"
ETCD_PROJECT_CONFIG_2="${ETCD_PROJECT_DIR}/etcd2.yaml"
# ETCD node path
ETCD_DST_DIR="/app/etcd-cluster"
ETCD_DST_CONFIG_0="${ETCD_DST_DIR}/etcd0/conf/etcd0.yaml"
ETCD_DST_CONFIG_1="${ETCD_DST_DIR}/etcd1/conf/etcd1.yaml"
ETCD_DST_CONFIG_2="${ETCD_DST_DIR}/etcd2/conf/etcd2.yaml"
ETCD_DST_CONFIG_0_BAK="${ETCD_DST_DIR}/etcd0/conf/etcd0.yaml.bak"
ETCD_DST_CONFIG_1_BAK="${ETCD_DST_DIR}/etcd1/conf/etcd1.yaml.bak"
ETCD_DST_CONFIG_2_BAK="${ETCD_DST_DIR}/etcd2/conf/etcd2.yaml.bak"

# local service dir list
LOCAL_API_GATEWAY_DIR="/app/local-api-gateway"
LOCAL_API_GATEWAY_DIR_LOG="${LOCAL_API_GATEWAY_DIR}/log"
LOCAL_API_GATEWAY_DIR_CONFIG="${LOCAL_API_GATEWAY_DIR}/config"
LOCAL_API_GATEWAY_DIR_DATA="${LOCAL_API_GATEWAY_DIR}/data"

LOCAL_API_GATEWAY_PROJECT_DIR="${SERVICE_CONFIG_DIR}/local-api-gateway"
LOCAL_API_GATEWAY_PROJECT_CONFIG_FILE="${LOCAL_API_GATEWAY_PROJECT_DIR}/local-api-gateway.yml"
LOCAL_API_GATEWAY_DST_CONFIG_FILE="${LOCAL_API_GATEWAY_DIR_CONFIG}/local-api-gateway.yml"
LOCAL_API_GATEWAY_DST_CONFIG_FILE_BAK="${LOCAL_API_GATEWAY_DIR_CONFIG}/local-api-gateway.yml.bak"

declare -a LOCAL_SERVICE_BASE_PATHS=(
    "${LOCAL_API_GATEWAY_DIR_LOG}"
    "${LOCAL_API_GATEWAY_DIR_CONFIG}"
    "${LOCAL_API_GATEWAY_DIR_DATA}"
)

declare -a SRC_PATHS=(
    "${PROMETHEUS_PROJECT_CONFIG_FILE}"
    "${GRAFANA_PROJECT_DATASOURCE_DIR}"
    "${GRAFANA_PROJECT_DASHBOARDS_FILE}"
    "${GRAFANA_PROJECT_PANEL_CADVISOR_FILE}"
    "${GRAFANA_PROJECT_PANEL_NODE_EXPORTER_FILE}"
    "${ETCD_PROJECT_CONFIG_0}"
    "${ETCD_PROJECT_CONFIG_1}"
    "${ETCD_PROJECT_CONFIG_2}"
    "${LOCAL_API_GATEWAY_PROJECT_CONFIG_FILE}"
)

declare -a DST_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE}"
    "${GRAFANA_DST_DATASOURCE_FILE}"
    "${GRAFANA_DST_DASHBOARDS_FILE}"
    "${GRAFANA_DST_PANEL_DEFAULT_FILE}"
    "${GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER}"
    "${ETCD_DST_CONFIG_0}"
    "${ETCD_DST_CONFIG_1}"
    "${ETCD_DST_CONFIG_2}"
    "${LOCAL_API_GATEWAY_DST_CONFIG_FILE}"
)

declare -a BAK_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE_BAK}"
    "${GRAFANA_DST_DATASOURCE_FILE_BAK}"
    "${GRAFANA_DST_DASHBOARDS_FILE_BAK}"
    "${GRAFANA_DST_PANEL_DEFAULT_FILE_BAK}"
    "${GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER_BAK}"
    "${ETCD_DST_CONFIG_0_BAK}"
    "${ETCD_DST_CONFIG_1_BAK}"
    "${ETCD_DST_CONFIG_2_BAK}"
    "${LOCAL_API_GATEWAY_DST_CONFIG_FILE_BAK}"
)