#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_CONFIG_DIR="${SCRIPT_DIR}/../service-config"

PROMETHEUS_PROJECT_DIR="${SERVICE_CONFIG_DIR}/prometheus"
PROMETHEUS_PROJECT_CONFIG_FILE="${PROMETHEUS_PROJECT_DIR}/prometheus.yml"
PROMETHEUS_DST_DIR="/app/prometheus/config"
PROMETHEUS_DST_CONFIG_FILE="${PROMETHEUS_DST_DIR}/prometheus.yml"
PROMETHEUS_DST_CONFIG_FILE_BAK="${PROMETHEUS_DST_DIR}/prometheus.yml.bak"

GRAFANA_PROJECT_DIR="${SERVICE_CONFIG_DIR}/grafana"
GRAFANA_PROJECT_PROVISIONING_DIR="${GRAFANA_PROJECT_DIR}/provisioning"
GRAFANA_PROJECT_DATASOURCE_DIR="${GRAFANA_PROJECT_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_DST_DIR="/app/grafana/config/grafana"
GRAFANA_DST_PROVISIONING_DIR="${GRAFANA_DST_DIR}/provisioning"
GRAFANA_DST_DATASOURCE_FILE="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_DST_DATASOURCE_FILE_BAK="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml.bak"

declare -a SRC_PATHS=(
    "${PROMETHEUS_PROJECT_CONFIG_FILE}"
    "${GRAFANA_PROJECT_DATASOURCE_DIR}"
)

declare -a DST_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE}"
    "${GRAFANA_DST_DATASOURCE_FILE}"
)

declare -a BAK_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE_BAK}"
    "${GRAFANA_DST_DATASOURCE_FILE_BAK}"
)