#!/bin/bash

# path on node and project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_CONFIG_DIR="${SCRIPT_DIR}/../service-config"

PROMETHEUS_PROJECT_DIR="${SERVICE_CONFIG_DIR}/prometheus"
PROMETHEUS_PROJECT_CONFIG_FILE="${PROMETHEUS_PROJECT_DIR}/prometheus.yml"
PROMETHEUS_DST_DIR="/app/prometheus/config"
PROMETHEUS_DST_CONFIG_FILE="${PROMETHEUS_DST_DIR}/prometheus.yml"
PROMETHEUS_DST_CONFIG_FILE_BAK="${PROMETHEUS_DST_DIR}/prometheus.yml.bak"

# Grafana project path
GRAFANA_PROJECT_DIR="${SERVICE_CONFIG_DIR}/grafana"
GRAFANA_PROJECT_PROVISIONING_DIR="${GRAFANA_PROJECT_DIR}/provisioning"
GRAFANA_PROJECT_DATASOURCE_DIR="${GRAFANA_PROJECT_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_PROJECT_DASHBOARDS_DIR="${GRAFANA_PROJECT_PROVISIONING_DIR}/dashboards"
GRAFANA_PROJECT_DASHBOARDS_FILE="${GRAFANA_PROJECT_DASHBOARDS_DIR}/dashboards.yml"
GRAFANA_PROJECT_PANEL_DIR="${GRAFANA_PROJECT_DASHBOARDS_DIR}/panel"
GRAFANA_PROJECT_PANEL_CADVISOR_FILE="${GRAFANA_PROJECT_PANEL_DIR}/cadvisor.json"
GRAFANA_PROJECT_PANEL_NODE_EXPORTER_FILE="${GRAFANA_PROJECT_PANEL_DIR}/node-exporter.json"
# Grafana node path
GRAFANA_DST_DIR="/app/grafana/config/grafana"
GRAFANA_DST_PROVISIONING_DIR="${GRAFANA_DST_DIR}/provisioning"
GRAFANA_DST_DATASOURCE_FILE="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml"
GRAFANA_DST_DATASOURCE_FILE_BAK="${GRAFANA_DST_PROVISIONING_DIR}/datasources/datasources.yml.bak"
GRAFANA_DST_DASHBOARDS_DIR="${GRAFANA_DST_PROVISIONING_DIR}/dashboards"
GRAFANA_DST_DASHBOARDS_FILE="${GRAFANA_DST_DASHBOARDS_DIR}/dashboards.yml"
GRAFANA_DST_DASHBOARDS_FILE_BAK="${GRAFANA_DST_DASHBOARDS_DIR}/dashboards.yml.bak"
GRAFANA_DST_PANEL_DIR="${GRAFANA_DST_DASHBOARDS_DIR}/panel"
GRAFANA_DST_PANEL_DEFAULT_FILE="${GRAFANA_DST_PANEL_DIR}/cadvisor.json"
GRAFANA_DST_PANEL_DEFAULT_FILE_BAK="${GRAFANA_DST_PANEL_DIR}/cadvisor.json.bak"
GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER="${GRAFANA_DST_PANEL_DIR}/node-exporter.json"
GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER_BAK="${GRAFANA_DST_PANEL_DIR}/node-exporter.json.bak"


declare -a SRC_PATHS=(
    "${PROMETHEUS_PROJECT_CONFIG_FILE}"
    "${GRAFANA_PROJECT_DATASOURCE_DIR}"
    "${GRAFANA_PROJECT_DASHBOARDS_FILE}"
    "${GRAFANA_PROJECT_PANEL_CADVISOR_FILE}"
    "${GRAFANA_PROJECT_PANEL_NODE_EXPORTER_FILE}"
)

declare -a DST_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE}"
    "${GRAFANA_DST_DATASOURCE_FILE}"
    "${GRAFANA_DST_DASHBOARDS_FILE}"
    "${GRAFANA_DST_PANEL_DEFAULT_FILE}"
    "${GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER}"
)

declare -a BAK_PATHS=(
    "${PROMETHEUS_DST_CONFIG_FILE_BAK}"
    "${GRAFANA_DST_DATASOURCE_FILE_BAK}"
    "${GRAFANA_DST_DASHBOARDS_FILE_BAK}"
    "${GRAFANA_DST_PANEL_DEFAULT_FILE_BAK}"
    "${GRAFANA_DST_PANEL_DEFAULT_NODE_EXPORTER_BAK}"
)